# Introduction

## WORK IN PROGRESS
This workshop is currently in development. 

## Introducing Digital Portfolios

A digital portfolio is an electronic collection of examples of your work. It is a tool that you can use in addition to your CV or resume to demonstrate your skills to potential collaborators or employers. Typically, these take the form of a website that is styled specifically to highlight the kind of skills you want to showcase.

You might think of your portfolio as public evidence of your data science skills.

For example, your portfolio might features your code (including documentation) and writing samples to show your ability to communicate effectively about data. You might use the text to illustrate how you approach problem-solving. 

## Approach

In this workshop, we will approach creating a digital data science portfolio through a series of steps. This is just one possible workflow. You might find that starting on a different step is more helpful for you, and that's ok. You can think of today's process as a checklist of things to do and consider, but they don't necessarily need to happen in this order.

Our suggested workflow is:

1. Set your goals for your portfolio.
2. Decide on a few project to include. (You can expand later.)
3. Decide on a platform for your portfolio.
4. Build a draft.
5. Get and implement feedback.
6. Share.



## Things to Consider

*This will probably expand into different sections*

### Plan your Portfolio
* What is your goal? What story to you want to tell? What impression/feeling/etc. do you want to inspire in the people viewing your portfolio?
* Which skills and projects do you want to highlight? Which skills and projects help you tell your story to the viewer?

* Links to public repositories like GitHub



