# Content

A good portfolio communicates and demonstrates your skills to the viewer. How you do that is something of a creative endeavor. We'll discuss some of the sections and information you could include, but what you include is up to you. You should not try to include everything, but rather pick the information that supports your goal. Every portfolio needs a projects and a contact information section, but the rest is up to you.

## Projects
The projects section is the heart of your portfolio and should appear in every portfolio. Here, you will provide a curated collection of projects you want to highlight. 

Project descriptions could be self-contained or they can link out to other websites and code repositories.

Consider including visuals here. If the project involves data visualization, such as a graph, workflow diagram, or map, you might choose that image as your visual. If the project was purely code, you could consider a stock image, just be aware of the image's license and only use images that are open licensed or you have permission to use.

The projects you list should support the goal you have for your portfolio. If my goal is to demonstrate my data visualization skills, I could include code that produces a visualization, but I wouldn't include a script that cleans data and doesn't produce a visualization. If I feel like that cleaning script is valuable in telling my story, maybe I need to redefine my goals for this portfolio. I might want to consider having sections for different kinds of projects.


**ACTIVITY 2:** Pick 3 projects you want to include in your portfolio. How do each of these support the goals of your portfolio?



## Contact Information
This section is also mandatory. You want people to know who you are so they can contact you if they are interested in your work. What information you provide is up to you. How do you decide? Reflect back on your goals. What contact information will help you achieve the goal for your portfolio?

Here are some types of contact information to consider:

* Name - the name you use on job applications 
* Other names you are well-known by (IRC handle, Discord handle)
* Email Address
* [OCRid](https://orcid.org/)
* [Google Scholar](https://scholar.google.com/) (if academic)
* Other academic profiles ([Academia.edu](https://www.academia.edu/), [Kudos](https://www.growkudos.com/), [Figshare](https://figshare.com/))
* [GitHub](https://github.com/) Profile
* Other tech community profiles ([Stack Exchange](https://stackexchange.com/), [Stack Overflow](https://stackoverflow.com/), [Reddit](https://www.reddit.com/)
* [LinkedIn](https://www.linkedin.com) Profile
* Website
* Work-related social media accounts that you use to represent yourself professionally (Twitter, Instagram, TikTok, YouTube, etc.)


## About

The about section is the place to describe yourself, your background, and to give your portfolio more context. You might talk about your experience in and out of your current field.

## Skills

## Publications



