# Plan Your Portfolio

## Develop Your Plan

Review your CV/resume. 

What is the main goal for your portfolio? What should it communicate to potential viewers?

What project(s) best match your goals? What projects are likely to most excite someone else? How can you integrate various media such as image or video?

What platform would you like to use?


| **ACTIVITY 3** breakout rooms - 20 min  | 
| Introduce yourselves and briefly what you study. |
| Take turns discussing a project and how you’d leverage it in your portfolio to meet your goals. |
| Are there any special considerations/concerns with that match? |


|**REPORT OUT: **|
| What barriers or concerns did your discussion uncover? |
| Were there any unique situations? |
| Which components of your portfolio are you most concerned about completing? |

## Strategies for Projects that can't be shared

You may not be able to share every important project you've worked on. Whether the data is personally identifiable data (PII), the paper associated with the project is awaiting publication, or the work is a part of a team effort that needs to be shared in another way, you may not be comfortable sharing a certain project on your personal portfolio. You still may want to share the skills you learned working on these kinds of projects in your portfolio, but you'll need to find ways to honor the private aspects of the project.

Depending on the nature of the project and the reasons you can't share it in its entirety, here are some potential options for including a project of this nature in your portfolio:

* Describe the project's goals and status without sharing the code or results
* Run a similar analysis with open licensed data with a similar structure or example data you crafted that has no relation to the original project's data to demonstrate your skills
* Write pseudocode or offer a workflow diagram in place of the code and data
* Link to the team's online repository or web pages describing the project


