# Additional Resources

UC Davis DataLab Resources

* [DataLab's ReadMe, Write Me! Workshop](https://datalab.ucdavis.edu/eventscalendar/readme-write-me/): documentation and metadata
* [DataLab Office Hours](https://datalab.ucdavis.edu/office-hours/)

GitHub Pages tutorials

* [GitHub Pages Website](https://pages.github.com/): getting started, tutorials, how to customize your site

UC Davis Internship & Career Center Resources (from resume to interview and beyond)

* [UC Davis ICC Resume & CV Resources](https://icc.ucdavis.edu/materials/resume)
* [UC Davis ICC Portfolio Rsources](https://icc.ucdavis.edu/materials/portfolios)

Personal Brand Development

* [UC Davis HR](https://hr.ucdavis.edu/departments/learning-dev/course-catalog/biz-ops/copyrights-uc-davis) and the [UC Davis Graduate School of Management](https://gsm.ucdavis.edu/event/personal-branding-workshop-how-brand-you) have both run workshops on developing your personal brand in the past. Contact them for updated workshop listings on this topic.

Other Resources:

* Kate Berg's presentation [Building Your Professional GIS Portfolio](https://www.youtube.com/watch?v=wBP-s4fP5uQ) for URISA
* {Free Datasets](https://www.dataquest.io/blog/free-datasets-for-projects/) to use in projects for your portfolio